// "use client"
import "bootstrap/dist/css/bootstrap.min.css";
import "./styles/globals.scss";

export const metadata = {
  title: "The Coding Buzz",
  description: "Generated by The Coding Buzz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>{children}</body>
    </html>
  );
}
